name: MyPy Type Check

on:
  push:
    branches: [ mypy-setup ]
  pull_request:
    branches: [ mypy-setup ]

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run MyPy
      run: mypy .

